version: "3"

services:

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=go-auth-nats-gateway
      - MYSQL_USER=user
      - MYSQL_PASSWORD=supersecret
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["/bin/bash", 'mysqladmin ping -u user -psupersecret']
      interval: 10s
      timeout: 2s
      retries: 10

  nats:
    image: nats:2.8
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js"]

  users:
    build:
      context: ./users
    image: marceloaguero/go-auth-nats-gateway-users:local
    environment:
      - PORT=8081
      - DB_DSN=user:supersecret@tcp(db:3306)
      - DB_NAME=go-auth-nats-gateway
      - NATS_URLS=nats://nats:4222
      - SUBJ_PREFIX=USERS
      - QUEUE=users
    ports:
      - "8081:8081"
    depends_on:
      - db
      - nats

  gateway:
    build:
      context: ./gateway
    image: marceloaguero/go-auth-nats-gateway-gateway:local
    environment:
      - PORT=8080
      - PATH_PREFIX=/gateway
      - NATS_URLS=nats://nats:4222
      - USERS_SUBJ_PREFIX=USERS
      - USERS_QUEUE=users
    ports:
      - "8080:8080"
    depends_on:
      - users

volumes:
  db-data:

